import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import { parseContractDocument } from "../src/contract.js";
import { buildSchemaDefinitionFromContract } from "../src/normalize-contract.js";
import { renderPythonModule } from "../src/render-python.js";
import type { SchemaDefinition } from "../src/types.js";

const OPTIONS = {
  moduleName: "models.py",
  headerComment: false,
  schemaHash: "test",
  packageVersion: "2.0.0-test"
};

async function renderFixture(
  name: string,
  options = OPTIONS
): Promise<{ definition: SchemaDefinition; output: string }> {
  const text = await readFile(new URL(`./fixtures/contracts/${name}`, import.meta.url), "utf8");
  const parsed = parseContractDocument(text);
  expect(parsed.diagnostics).toEqual([]);
  const { definition } = buildSchemaDefinitionFromContract(parsed.document!, true);
  return { definition, output: renderPythonModule(definition, options) };
}

function renderDoc(doc: Record<string, unknown>): { definition: SchemaDefinition; output: string } {
  const text = JSON.stringify({
    schemaVersion: "1",
    targetFamily: "sql",
    target: "postgres",
    ...doc
  });
  const parsed = parseContractDocument(text);
  expect(parsed.diagnostics).toEqual([]);
  const { definition } = buildSchemaDefinitionFromContract(parsed.document!, true);
  return { definition, output: renderPythonModule(definition, OPTIONS) };
}

describe("render contract: basic models", () => {
  it("renders checks, native enums, uuid factories, and timestamps", async () => {
    const { output } = await renderFixture("basic-postgres.json");

    expect(output).toContain("CheckConstraint(");
    expect(output).toContain("user_priority_check_dea9d0ab");
    expect(output).toContain("class Role(str, Enum):");
    expect(output).toContain("SAEnum(Role");
    expect(output).toContain("default_factory=uuid4");
    expect(output).toContain("from uuid import UUID, uuid4");
    expect(output).toContain("onupdate=func.now()");
    expect(output).toContain("back_populates='posts'");
    expect(output).toContain("Index('post_userId_idx_a489d58a'");
  });

  it("renders the file header when enabled", async () => {
    const { output } = await renderFixture("basic-postgres.json", {
      moduleName: "models.py",
      headerComment: true,
      schemaHash: "abc123",
      packageVersion: "2.0.0-test"
    });

    expect(output).toContain("# This file is generated by prisma-sqlmodel-gen.");
    expect(output).toContain("# Package version: 2.0.0-test");
    expect(output).toContain("# Schema hash: abc123");
    expect(output).toContain("# Module: models.py");
  });

  it("renders text enums as TEXT columns with Enum annotations", async () => {
    const { output } = await renderFixture("basic-postgres.json");

    expect(output).toContain("class Priority(str, Enum):");
    expect(output).toContain("Column(TEXT()");
    expect(output).toContain("default=Priority.LOW");
    expect(output).not.toContain("SAEnum(Priority");
  });
});

describe("render contract: expression indexes and scalar imports", () => {
  it("renders expression and access-method indexes", async () => {
    const { output } = await renderFixture("relations-types.json");

    expect(output).toContain("text('lower(title)')");
    expect(output).toContain("post_title_lower_40104d8c");
    expect(output).toContain("postgresql_using='hash'");
    expect(output).toContain("ondelete='SET NULL'");
    expect(output).toContain("server_default=text('upper(\\'x\\')')");
  });

  it("imports date and time annotations", async () => {
    const { output } = await renderFixture("relations-types.json");

    expect(output).toContain("from datetime import date, datetime, time");
    expect(output).toContain("from decimal import Decimal");
  });
});

describe("render contract: many-to-many and composite keys", () => {
  it("renders link models and composite constraints", async () => {
    const { output } = await renderFixture("join-composite.json");

    expect(output).toContain("link_model=BookTag");
    expect(output).toContain("PrimaryKeyConstraint('orgId', 'teamId')");
    expect(output).toContain("ForeignKeyConstraint(");
  });

  it("omits back_populates for one-sided relations", async () => {
    const { output } = await renderFixture("join-composite.json");

    const tenantLine = output.split("\n").find((line) => line.includes("tenant:"))!;
    expect(tenantLine).toContain("Relationship(sa_relationship_kwargs=");
    expect(tenantLine).not.toContain("back_populates");
    expect(output).not.toContain("back_populates=''");
  });
});

describe("render contract: value objects and variants", () => {
  it("renders value objects ahead of the models that use them", async () => {
    const { output } = await renderFixture("advanced.json");

    expect(output).toContain("class Address(SQLModel):");
    expect(output).toContain("street: str");
    expect(output).toContain("zip: str | None = None");
    expect(output.indexOf("class Address(SQLModel):")).toBeLessThan(output.indexOf("class Doc("));
    expect(output).toContain("address: Address | None = Field(");
  });

  it("renders checks and partial indexes", async () => {
    const { output } = await renderFixture("advanced.json");

    expect(output).toContain("doc_email_len_5aab927d");
    expect(output).toContain("doc_email_active_106036f9");
    expect(output).toContain("postgresql_where=text(");
  });

  it("renders single-table inheritance", async () => {
    const { output } = await renderFixture("advanced.json");

    expect(output).toContain("__mapper_args__ = {'polymorphic_on': 'type'}");
    expect(output).toContain("class Bug(Task):");
    expect(output).toContain("__mapper_args__ = {'polymorphic_identity': 'bug'}");
    const bugStart = output.indexOf("class Bug(Task):");
    const nextClass = output.indexOf("\n\nclass ", bugStart + 1);
    const bugBlock = output.slice(bugStart, nextClass === -1 ? undefined : nextClass);
    expect(bugBlock).not.toContain("__tablename__");
    expect(bugBlock).not.toContain("__table_args__");
    expect(output.indexOf("class Task(SQLModel, table=True):")).toBeLessThan(bugStart);
  });

  it("renders joined-table inheritance", async () => {
    const { output } = await renderFixture("joined-variant.json");

    expect(output).toContain("class Bug(Task, table=True):");
    expect(output).toContain("__tablename__ = 'bug'");
    expect(output).toContain("__mapper_args__ = {'polymorphic_identity': 'bug'}");
  });
});

describe("render contract: integer enums and precisions", () => {
  it("renders integer enums as int Enum classes over INTEGER columns", async () => {
    const { output } = await renderFixture("scalars.json");

    expect(output).toContain("class Level(int, Enum):");
    expect(output).toContain("LOW = 1");
    expect(output).toContain("Column(INTEGER()");
    expect(output).not.toContain("SAEnum(Level");
  });

  it("renders float, bigint, and precision type arguments", async () => {
    const { output } = await renderFixture("scalars.json");

    expect(output).toContain("DOUBLE_PRECISION()");
    expect(output).toContain("BIGINT()");
    expect(output).toContain("TIMESTAMP(precision=3)");
    expect(output).toContain("precision=6");
    expect(output).toContain("TIME(precision=2)");
    expect(output).toContain("TIME(timezone=True)");
  });
});

describe("render contract: synthetic edge cases", () => {
  it("renders unique indexes and unnamed checks", () => {
    const { definition, output } = renderDoc({
      storage: {
        namespaces: {
          public: {
            entries: {
              table: {
                t: {
                  columns: {
                    a: { nativeType: "text", codecId: "pg/text@1", nullable: false },
                    b: { nativeType: "text", codecId: "pg/text@1", nullable: true }
                  },
                  indexes: [{ columns: ["b"], name: "u_b", unique: true }],
                  checks: [{ expression: "a <> b" }]
                }
              }
            }
          }
        }
      },
      domain: {
        namespaces: {
          public: {
            models: {
              M: {
                fields: {},
                relations: {},
                storage: { table: "t", namespaceId: "public", fields: {} }
              }
            }
          }
        }
      }
    });

    const unique = definition.models[0]!.constraints.find((entry) => entry.name === "u_b")!;
    expect(unique.unique).toBe(true);
    expect(output).toContain("Index('u_b', 'b', unique=True)");
    expect(output).toContain("CheckConstraint('a <> b')");
    expect(output).not.toContain("CheckConstraint('a <> b', name=");
  });

  it("renders variants with missing bases using the declared name", () => {
    const output = renderPythonModule(
      {
        provider: "postgresql",
        enums: [],
        models: [
          {
            name: "Orphan",
            pythonName: "Orphan",
            tableName: "orphan",
            scalarFields: [],
            relationFields: [],
            constraints: [],
            foreignKeys: [],
            inheritance: { kind: "variant", baseModel: "Missing", value: "x", ownsTable: false }
          }
        ]
      },
      OPTIONS
    );

    expect(output).toContain("class Orphan(Missing):");
  });

  it("renders value object lists and empty value objects", () => {
    const output = renderPythonModule(
      {
        provider: "postgresql",
        enums: [],
        models: [],
        valueObjects: [
          {
            name: "Tags",
            pythonName: "Tags",
            fields: [{ name: "names", pythonName: "names", pythonType: "str", isNullable: false, isList: true }]
          },
          { name: "Empty", pythonName: "Empty", fields: [] }
        ]
      },
      OPTIONS
    );

    expect(output).toContain("names: list[str]");
    expect(output).toContain("class Empty(SQLModel):\n    pass");
  });

  it("orders cyclic value objects without hanging", () => {
    const output = renderPythonModule(
      {
        provider: "postgresql",
        enums: [],
        models: [],
        valueObjects: [
          {
            name: "A",
            pythonName: "A",
            fields: [{ name: "b", pythonName: "b", pythonType: "B", isNullable: true, isList: false }]
          },
          {
            name: "B",
            pythonName: "B",
            fields: [{ name: "a", pythonName: "a", pythonType: "A", isNullable: true, isList: false }]
          }
        ]
      },
      OPTIONS
    );

    expect(output).toContain("class A(SQLModel):");
    expect(output).toContain("class B(SQLModel):");
    expect(output.indexOf("class B(SQLModel):")).toBeLessThan(output.indexOf("class A(SQLModel):"));
  });
});

describe("render contract: real Prisma 8 output", () => {
  it("renders an emitted realworld contract", async () => {
    const { output } = await renderFixture("realworld.json");

    expect(output).toContain("class PostTag(SQLModel, table=True):");
    expect(output).toContain("back_populates='tags'");
    expect(output).toContain("PrimaryKeyConstraint('postId', 'tagId')");
    expect(output).toContain("UniqueConstraint('groupId', 'role')");
    expect(output).toContain("ondelete='CASCADE'");
    expect(output).toContain("onupdate='CASCADE'");
    expect(output).toContain("remote_side");
    expect(output).toContain("TIMESTAMP(precision=3, timezone=True)");
    expect(output).toContain("ARRAY(TEXT())");
    expect(output).toContain("default_factory=uuid4");
    expect(output).toContain("default=0");
    expect(output).toContain("default=Role.MEMBER");
    expect(output).toContain("CheckConstraint");
  });

  it("renders an emitted user-schema contract", async () => {
    const { output } = await renderFixture("user-schema.json");

    expect(output).toContain("class Article(SQLModel, table=True):");
    expect(output).toContain("class FilingChunk(SQLModel, table=True):");
    expect(output).toContain("Index('pgarticle_authors', 'authors', postgresql_using='gin')");
    expect(output).toContain("Index('pgarticle_company_created_at_desc', 'company_id', 'created_at')");
    expect(output).toContain("Index('pgarticle_created_at_desc', 'created_at')");
    expect(output).toContain(
      "UniqueConstraint('filing_id', 'kind', 'ordinal', name='pgfilingchunk_filing_kind_ordinal')"
    );
    expect(output).toContain("UniqueConstraint('ticker', name='pgcompany_ticker')");
    expect(output).toContain("UniqueConstraint('source_url', name='pgfiling_source_url')");
    expect(output).not.toContain("unique=True");
    expect(output).toContain("server_default=text('gen_random_uuid()')");
    expect(output).toContain("TIMESTAMP(precision=6)");
    expect(output).toContain("PG_UUID(as_uuid=True)");
    expect(output).toContain("Column(JSONB(), nullable=False)");
    expect(output).not.toContain("JSON()");
    expect(output).toContain("VARCHAR(255)");
    expect(output).toContain("ondelete='CASCADE'");
    expect(output).toContain("back_populates='articles'");
  });
});
