import type {
  ConstraintDefinition,
  ConstraintFieldDefinition,
  EnumDefinition,
  ForeignKeyDefinition,
  ModelDefinition,
  NativeType,
  RelationFieldDefinition,
  ScalarFieldDefinition,
  SchemaDefinition,
  ValueObjectDefinition
} from "./types.js";
import { quotePythonString, toPythonIdentifier } from "./utils.js";

type ImportState = {
  standard: Set<string>;
  sqlmodel: Set<string>;
  sqlalchemy: Set<string>;
  postgres: Set<string>;
};

type RenderContext = {
  modelNameMap: Map<string, string>;
  enumNameMap: Map<string, string>;
  fieldNameMap: Map<string, Map<string, string>>;
};

const SCALAR_PRISMA_TYPES = new Set([
  "String",
  "Boolean",
  "Int",
  "BigInt",
  "Float",
  "Decimal",
  "Bytes",
  "DateTime",
  "Json",
  "Jsonb"
]);

const NONE_DEFAULT_FUNCTIONS = new Set(["autoincrement", "dbgenerated", "now", "now_client", "uuid"]);

export function renderPythonModule(
  schema: SchemaDefinition,
  options: {
    moduleName: string;
    headerComment: boolean;
    schemaHash: string;
    packageVersion: string;
  }
): string {
  const imports: ImportState = {
    standard: new Set(["from typing import Any, Optional"]),
    sqlmodel: new Set(["Field", "Relationship", "SQLModel"]),
    sqlalchemy: new Set(["Column"]),
    postgres: new Set()
  };
  const context = buildRenderContext(schema);

  collectImports(schema, imports);

  const sections: string[] = [];

  if (options.headerComment) {
    sections.push(
      [
        "# This file is generated by prisma-sqlmodel-gen.",
        `# Package version: ${options.packageVersion}`,
        `# Schema hash: ${options.schemaHash}`,
        `# Module: ${options.moduleName}`,
        "# Do not edit this file directly."
      ].join("\n")
    );
  }

  sections.push(renderImports(imports));

  const valueObjects = sortValueObjects(schema.valueObjects ?? []);
  if (valueObjects.length > 0) {
    sections.push(valueObjects.map((entry) => renderValueObject(entry)).join("\n\n"));
  }

  if (schema.enums.length > 0) {
    sections.push(schema.enums.map((entry) => renderEnum(entry)).join("\n\n"));
  }

  const regularModels = sortModelsForEmission(schema.models);

  sections.push(regularModels.map((model) => renderModel(model, schema, context)).join("\n\n\n"));

  return `${sections.filter(Boolean).join("\n\n")}\n`;
}

function buildRenderContext(schema: SchemaDefinition): RenderContext {
  return {
    modelNameMap: new Map(schema.models.map((model) => [model.name, model.pythonName])),
    enumNameMap: new Map(schema.enums.map((entry) => [entry.name, entry.pythonName])),
    fieldNameMap: new Map(
      schema.models.map((model) => [
        model.name,
        new Map(
          [...model.scalarFields, ...model.relationFields].map((field) => [field.name, field.pythonName])
        )
      ])
    )
  };
}

function collectImports(schema: SchemaDefinition, imports: ImportState): void {
  if (schema.enums.length > 0) {
    imports.standard.add("from enum import Enum");
    imports.sqlalchemy.add("Enum as SAEnum");
  }

  const datetimeNames = new Set<string>();
  const uuidNames = new Set<string>();

  for (const valueObject of schema.valueObjects ?? []) {
    for (const field of valueObject.fields) {
      collectAnnotationImports(field.pythonType, imports, datetimeNames, uuidNames);
    }
  }

  for (const model of schema.models) {
    if (model.tableSchema) {
      imports.standard.add("from typing import Any, Optional");
    }

    for (const field of model.scalarFields) {
      collectAnnotationImports(field.pythonType, imports, datetimeNames, uuidNames);
      if (field.prismaType === "Json" && field.nativeType?.name !== "Json") {
        imports.postgres.add("JSONB");
      }
      if (field.isUpdatedAt) {
        imports.sqlalchemy.add("func");
      }
      if (field.isList) {
        imports.postgres.add("ARRAY");
      }
      collectTypeImports(field.nativeType, imports, field);

      if (field.defaultValue && typeof field.defaultValue === "object" && "name" in field.defaultValue) {
        const name = String(field.defaultValue.name);
        if (name === "uuid") {
          uuidNames.add("uuid4");
        }
        if (name === "now_client") {
          datetimeNames.add("datetime");
          datetimeNames.add("timezone");
        }
        if (name === "dbgenerated") {
          imports.sqlalchemy.add("text");
        }
        if (name === "now") {
          imports.sqlalchemy.add("func");
        }
      }
      if (getForeignKeyFieldCount(field.foreignKey) === 1) {
        imports.sqlalchemy.add("ForeignKey");
      }
    }

    for (const constraint of model.constraints) {
      const { fields } = constraint;
      if (constraint.kind === "unique") {
        if (fields.some((field) => field.sort)) {
          imports.sqlalchemy.add("Index");
          if (fields.some((field) => field.sort === "desc")) {
            imports.sqlalchemy.add("desc");
          }
          if (fields.some((field) => field.sort === "asc")) {
            imports.sqlalchemy.add("asc");
          }
        } else {
          imports.sqlalchemy.add("UniqueConstraint");
        }
      }
      if (constraint.kind === "index") {
        imports.sqlalchemy.add("Index");
        if (fields.some((field) => field.sort === "desc")) {
          imports.sqlalchemy.add("desc");
        }
        if (fields.some((field) => field.sort === "asc")) {
          imports.sqlalchemy.add("asc");
        }
        if (constraint.expression || constraint.where) {
          imports.sqlalchemy.add("text");
        }
      }
      if (constraint.kind === "primary_key" && fields.length > 1) {
        imports.sqlalchemy.add("PrimaryKeyConstraint");
      }
    }

    for (const foreignKey of model.foreignKeys) {
      imports.sqlalchemy.add("ForeignKeyConstraint");
    }

    if ((model.checks ?? []).length > 0) {
      imports.sqlalchemy.add("CheckConstraint");
    }
  }

  if (datetimeNames.size > 0) {
    imports.standard.add(`from datetime import ${[...datetimeNames].sort().join(", ")}`);
  }
  if (uuidNames.size > 0) {
    imports.standard.add(`from uuid import ${[...uuidNames].sort().join(", ")}`);
  }
}

function collectAnnotationImports(
  pythonType: string,
  imports: ImportState,
  datetimeNames: Set<string>,
  uuidNames: Set<string>
): void {
  if (pythonType === "Decimal") {
    imports.standard.add("from decimal import Decimal");
  }
  if (pythonType === "datetime") {
    datetimeNames.add("datetime");
  }
  if (pythonType === "date") {
    datetimeNames.add("date");
  }
  if (pythonType === "time") {
    datetimeNames.add("time");
  }
  if (pythonType === "UUID") {
    uuidNames.add("UUID");
  }
}

function collectTypeImports(
  nativeType: NativeType | undefined,
  imports: ImportState,
  field: ScalarFieldDefinition
): void {
  if (!nativeType) {
    switch (field.prismaType) {
      case "String":
        imports.sqlalchemy.add("String");
        return;
      case "Boolean":
        imports.sqlalchemy.add("Boolean");
        return;
      case "Int":
        imports.sqlalchemy.add("Integer");
        return;
      case "BigInt":
        imports.sqlalchemy.add("BigInteger");
        return;
      case "Float":
        imports.sqlalchemy.add("Float");
        return;
      case "Decimal":
        imports.sqlalchemy.add("Numeric");
        return;
      case "Bytes":
        imports.sqlalchemy.add("LargeBinary");
        return;
      case "DateTime":
        imports.sqlalchemy.add("DateTime");
        return;
      default:
        return;
    }
  }

  const mapping = mapPostgresType(nativeType);
  imports.postgres.add(mapping.importName ?? mapping.typeName);
}

function renderImports(imports: ImportState): string {
  const lines: string[] = [...imports.standard].sort();
  lines.push(`from sqlmodel import ${[...imports.sqlmodel].sort().join(", ")}`);
  lines.push(`from sqlalchemy import ${[...imports.sqlalchemy].sort().join(", ")}`);
  if (imports.postgres.size > 0) {
    lines.push(`from sqlalchemy.dialects.postgresql import ${[...imports.postgres].sort().join(", ")}`);
  }

  return lines.join("\n");
}

function renderEnum(entry: EnumDefinition): string {
  const base = entry.storage === "integer" ? "int" : "str";
  const body = entry.values
    .map(
      (value) =>
        `    ${value.pythonName} = ${typeof value.value === "string" ? quotePythonString(value.value) : String(value.value)}`
    )
    .join("\n");
  return `class ${entry.pythonName}(${base}, Enum):\n${body}`;
}

function renderValueObject(entry: ValueObjectDefinition): string {
  const lines = [`class ${entry.pythonName}(SQLModel):`];
  for (const field of entry.fields) {
    const annotation = field.isList ? `list[${field.pythonType}]` : field.pythonType;
    if (field.isNullable) {
      lines.push(`    ${field.pythonName}: ${annotation} | None = None`);
    } else {
      lines.push(`    ${field.pythonName}: ${annotation}`);
    }
  }
  if (lines.length === 1) {
    lines.push("    pass");
  }
  return lines.join("\n");
}

function sortModelsForEmission(models: ModelDefinition[]): ModelDefinition[] {
  const rank = (model: ModelDefinition): number => {
    if (model.inheritance?.kind === "variant") {
      return 2;
    }
    if (model.relationFields.some((field) => field.linkModelName !== undefined)) {
      return 1;
    }
    return 0;
  };
  return models
    .map((model, index) => ({ model, index, rank: rank(model) }))
    .sort((left, right) => left.rank - right.rank || left.index - right.index)
    .map((entry) => entry.model);
}

function sortValueObjects(entries: ValueObjectDefinition[]): ValueObjectDefinition[] {
  const byName = new Map(entries.map((entry) => [entry.pythonName, entry]));
  const dependencies = new Map(
    entries.map((entry) => [
      entry.pythonName,
      entry.fields.flatMap((field) => {
        const target = byName.get(field.pythonType);
        return target ? [target] : [];
      })
    ])
  );
  const sorted: ValueObjectDefinition[] = [];
  const visited = new Set<string>();
  const visit = (entry: ValueObjectDefinition, stack: string[]): void => {
    if (visited.has(entry.pythonName)) {
      return;
    }
    visited.add(entry.pythonName);
    for (const dependency of dependencies.get(entry.pythonName) as ValueObjectDefinition[]) {
      if (!stack.includes(dependency.pythonName)) {
        visit(dependency, [...stack, entry.pythonName]);
      }
    }
    sorted.push(entry);
  };
  for (const entry of entries) {
    visit(entry, []);
  }
  return sorted;
}

function renderModel(model: ModelDefinition, schema: SchemaDefinition, context: RenderContext): string {
  const inheritance = model.inheritance;
  const isSharedTableVariant = inheritance?.kind === "variant" && !inheritance.ownsTable;
  const baseClass =
    inheritance?.kind === "variant"
      ? (context.modelNameMap.get(inheritance.baseModel) ?? toPythonIdentifier(inheritance.baseModel))
      : "SQLModel";
  const classLine = isSharedTableVariant
    ? `class ${model.pythonName}(${baseClass}):`
    : inheritance?.kind === "variant"
      ? `class ${model.pythonName}(${baseClass}, table=True):`
      : `class ${model.pythonName}(SQLModel, table=True):`;
  const lines: string[] = [classLine];
  if (!isSharedTableVariant) {
    lines.push(`    __tablename__ = ${quotePythonString(model.tableName)}`);
  }

  const mapperArgs = renderMapperArgs(model, context);
  if (mapperArgs) {
    lines.push(`    __mapper_args__ = ${mapperArgs}`);
  }

  const sanitizationComments = renderSanitizationComments(model);
  for (const comment of sanitizationComments) {
    lines.push(`    ${comment}`);
  }

  const tableArgs = renderTableArgs(model, schema, context);
  if (tableArgs) {
    lines.push(`    __table_args__ = ${tableArgs}`);
  }

  for (const field of model.scalarFields) {
    lines.push(`    ${renderScalarField(field, model, schema, context)}`);
  }

  for (const field of model.relationFields) {
    lines.push(`    ${renderRelationField(field, model, schema, context)}`);
  }

  if (lines.length === 2 && !mapperArgs) {
    lines.push("    pass");
  }

  return lines.join("\n");
}

function renderMapperArgs(model: ModelDefinition, context: RenderContext): string | undefined {
  const inheritance = model.inheritance;
  if (!inheritance) {
    return undefined;
  }
  if (inheritance.kind === "variant") {
    return `{'polymorphic_identity': ${quotePythonString(inheritance.value)}}`;
  }
  const discriminator = resolveFieldPythonName(model.name, inheritance.discriminatorField, context);
  return `{'polymorphic_on': ${quotePythonString(discriminator)}}`;
}

function renderSanitizationComments(model: ModelDefinition): string[] {
  const comments: string[] = [];
  if (model.pythonName !== model.name) {
    comments.push(`# Prisma model '${model.name}' emitted as Python class '${model.pythonName}'.`);
  }

  for (const field of [...model.scalarFields, ...model.relationFields]) {
    if (field.pythonName !== field.name) {
      comments.push(`# Prisma field '${field.name}' emitted as Python attribute '${field.pythonName}'.`);
    }
  }

  return comments;
}

function renderTableArgs(model: ModelDefinition, schema: SchemaDefinition, context: RenderContext): string | undefined {
  const args: string[] = [];

  for (const constraint of model.constraints) {
    if (constraint.kind === "primary_key" && constraint.fields.length > 1) {
      args.push(renderConstraintCall("PrimaryKeyConstraint", constraint, model, context));
    }
    if (constraint.kind === "unique") {
      args.push(renderConstraintCall("UniqueConstraint", constraint, model, context));
    }
    if (constraint.kind === "index") {
      args.push(renderConstraintCall("Index", constraint, model, context));
    }
  }

  for (const foreignKey of model.foreignKeys) {
    args.push(renderForeignKeyConstraint(foreignKey, model, schema));
  }

  for (const check of model.checks ?? []) {
    const checkArgs = [quotePythonString(check.expression)];
    if (check.name) {
      checkArgs.push(`name=${quotePythonString(check.name)}`);
    }
    args.push(`CheckConstraint(${checkArgs.join(", ")})`);
  }

  if (model.tableSchema) {
    args.push(`{"schema": ${quotePythonString(model.tableSchema)}}`);
  }

  if (args.length === 0) {
    return undefined;
  }

  return `(${args.join(", ")},)`;
}

function renderConstraintCall(
  helper: "PrimaryKeyConstraint" | "UniqueConstraint" | "Index",
  constraint: ConstraintDefinition,
  model: ModelDefinition,
  context: RenderContext
): string {
  const { fields } = constraint;
  const fieldArgs = fields.map((field) => renderConstraintFieldExpression(field, helper, model, context));
  const anyDialectOptions = fields.some((field) => field.sort);

  if ((helper === "UniqueConstraint" || helper === "Index") && anyDialectOptions) {
    const args = [
      ...(constraint.name ? [quotePythonString(constraint.name)] : []),
      ...fieldArgs
    ];
    const kwargs: string[] = [];
    if (helper === "UniqueConstraint") {
      kwargs.push("unique=True");
    }
    return `Index(${[...args, ...kwargs].join(", ")})`;
  }

  const columnNames = fields.map((field) => {
    const scalarField = model.scalarFields.find((candidate) => candidate.name === field.name);
    return quotePythonString(scalarField?.columnName ?? field.name);
  });

  if (helper === "Index") {
    const args = [
      ...(constraint.name ? [quotePythonString(constraint.name)] : []),
      ...fieldArgs
    ];
    if (constraint.expression) {
      args.push(`text(${quotePythonString(constraint.expression)})`);
    }
    if (constraint.unique) {
      args.push("unique=True");
    }
    const postgresUsing = buildPostgresUsingKwarg(constraint);
    if (postgresUsing) {
      args.push(postgresUsing);
    }
    if (constraint.where) {
      args.push(`postgresql_where=text(${quotePythonString(constraint.where)})`);
    }
    return `Index(${args.join(", ")})`;
  }

  const args = [...columnNames];
  if (constraint.name) {
    args.push(`name=${quotePythonString(constraint.name)}`);
  }
  return `${helper}(${args.join(", ")})`;
}

function renderConstraintFieldExpression(
  field: ConstraintFieldDefinition,
  helper: "PrimaryKeyConstraint" | "UniqueConstraint" | "Index",
  model: ModelDefinition,
  context: RenderContext
): string {
  const scalarField = model.scalarFields.find((candidate) => candidate.name === field.name);
  const columnName = scalarField?.columnName ?? field.name;

  if (helper === "Index" || helper === "UniqueConstraint") {
    if (field.sort === "desc") {
      return `desc(${quotePythonString(columnName)})`;
    }
    if (field.sort === "asc") {
      return `asc(${quotePythonString(columnName)})`;
    }
  }

  if (helper === "Index" && scalarField && scalarField.pythonName !== field.name) {
    return quotePythonString(columnName);
  }

  return quotePythonString(columnName);
}

const SUPPORTED_POSTGRES_INDEX_USING = new Set(["btree", "brin", "gin", "hash", "spgist"]);

function buildPostgresUsingKwarg(constraint: ConstraintDefinition): string | undefined {
  if (!constraint.algorithm) {
    return undefined;
  }

  const normalized = constraint.algorithm.toLowerCase();
  if (SUPPORTED_POSTGRES_INDEX_USING.has(normalized)) {
    return "postgresql_using='" + normalized + "'";
  }

  return undefined;
}

function renderForeignKeyConstraint(
  foreignKey: ForeignKeyDefinition,
  model: ModelDefinition,
  schema: SchemaDefinition
): string {
  const localColumns = getForeignKeyFields(foreignKey)
    .map((fieldName) => quotePythonString(resolveScalarColumnName(model, fieldName)))
    .join(", ");
  const targetColumns = getForeignKeyTargetFields(foreignKey)
    .map((fieldName) =>
      quotePythonString(buildTargetColumnReference(schema, foreignKey.targetModel, fieldName))
    )
    .join(", ");
  const args = [`[${localColumns}]`, `[${targetColumns}]`];

  if (foreignKey.name) {
    args.push(`name=${quotePythonString(foreignKey.name)}`);
  }
  if (foreignKey.onDelete) {
    args.push(`ondelete=${quotePythonString(foreignKey.onDelete)}`);
  }
  if (foreignKey.onUpdate) {
    args.push(`onupdate=${quotePythonString(foreignKey.onUpdate)}`);
  }

  return `ForeignKeyConstraint(${args.join(", ")})`;
}

function renderScalarField(
  field: ScalarFieldDefinition,
  model: ModelDefinition,
  schema: SchemaDefinition,
  context: RenderContext
): string {
  const annotation = renderScalarAnnotation(field, context);
  const columnParts = buildColumnParts(field, model, schema, context);
  const defaultClause = renderColumnDefault(field, context);
  const columnKwargs = buildColumnKwargs(field, model, defaultClause.column);
  columnParts.push(...columnKwargs);

  const fieldArgs = [`sa_column=Column(${columnParts.join(", ")})`];
  if (defaultClause.field) {
    fieldArgs.push(defaultClause.field);
  } else if (field.isNullable || shouldSetDefaultNone(field)) {
    fieldArgs.push("default=None");
  }

  return `${field.pythonName}: ${annotation} = Field(${fieldArgs.join(", ")})`;
}

function buildColumnParts(
  field: ScalarFieldDefinition,
  model: ModelDefinition,
  schema: SchemaDefinition,
  context: RenderContext
): string[] {
  const parts: string[] = [];

  if (field.columnName !== field.name) {
    parts.push(quotePythonString(field.columnName));
  }

  parts.push(renderColumnType(field, model, schema, context));

  if (field.foreignKey && getForeignKeyFieldCount(field.foreignKey) === 1) {
    const args = [quotePythonString(buildTargetColumnReference(schema, field.foreignKey.targetModel, getForeignKeyTargetFields(field.foreignKey)[0]))];
    if (field.foreignKey.name) {
      args.push(`name=${quotePythonString(field.foreignKey.name)}`);
    }
    if (field.foreignKey.onDelete) {
      args.push(`ondelete=${quotePythonString(field.foreignKey.onDelete)}`);
    }
    if (field.foreignKey.onUpdate) {
      args.push(`onupdate=${quotePythonString(field.foreignKey.onUpdate)}`);
    }
    parts.push(`ForeignKey(${args.join(", ")})`);
  }

  return parts;
}

function buildColumnKwargs(
  field: ScalarFieldDefinition,
  model: ModelDefinition,
  renderedDefault?: string
): string[] {
  const kwargs: string[] = [];

  const hasCompositePrimaryKey = model.constraints.some(
    (constraint) => constraint.kind === "primary_key" && constraint.fields.length > 1
  );

  if (field.isUnique && !field.isId) {
    kwargs.push("unique=True");
  }

  if (!hasCompositePrimaryKey && field.isId) {
    kwargs.push("primary_key=True");
  }

  kwargs.push(field.isNullable ? "nullable=True" : "nullable=False");

  if (renderedDefault) {
    kwargs.push(renderedDefault);
  }

  if (field.isUpdatedAt) {
    kwargs.push("onupdate=func.now()");
  }

  return kwargs;
}

function renderRelationField(
  field: RelationFieldDefinition,
  model: ModelDefinition,
  schema: SchemaDefinition,
  context: RenderContext
): string {
  const args: string[] = [];
  if (field.backPopulates) {
    args.push(
      `back_populates=${quotePythonString(resolveFieldPythonName(field.targetModel, field.backPopulates, context))}`
    );
  }

  if (field.linkModelName) {
    args.push(`link_model=${field.linkModelName}`);
  }

  const relationshipKwargs = buildRelationshipKwargs(model, field, schema, context);
  if (relationshipKwargs.length > 0) {
    args.push(`sa_relationship_kwargs={${relationshipKwargs.join(", ")}}`);
  }

  return `${field.pythonName}: ${renderRelationAnnotation(field, context)} = Relationship(${args.join(", ")})`;
}

function renderRelationshipForeignKeyReference(
  model: ModelDefinition,
  field: RelationFieldDefinition,
  schema: SchemaDefinition,
  context: RenderContext
): string | undefined {
  if (field.linkModelName) {
    return undefined;
  }

  if (field.foreignKeyFieldNames.length > 0) {
    return renderForeignKeyReference(model, field, context);
  }

  const targetModel = schema.models.find((candidate) => candidate.name === field.targetModel);
  const counterpart = findRelationCounterpart(targetModel, field);

  if (!targetModel || !counterpart || counterpart.foreignKeyFieldNames.length === 0) {
    return undefined;
  }

  return renderForeignKeyReference(targetModel, counterpart, context);
}

function renderForeignKeyReference(
  model: ModelDefinition,
  field: RelationFieldDefinition,
  context: RenderContext
): string {
  const modelName = model.pythonName;
  const references = field.foreignKeyFieldNames.map((name) => `${modelName}.${resolveFieldPythonName(model.name, name, context)}`);
  return references.length === 1 ? references[0] : `[${references.join(", ")}]`;
}

function renderRelationAnnotation(field: RelationFieldDefinition, context: RenderContext): string {
  const targetType = context.modelNameMap.get(field.targetModel) ?? field.targetModel;
  if (field.isList) {
    return `list['${targetType}']`;
  }

  return field.isNullable ? `Optional['${targetType}']` : `'${targetType}'`;
}

function buildRelationshipKwargs(
  model: ModelDefinition,
  field: RelationFieldDefinition,
  schema: SchemaDefinition,
  context: RenderContext
): string[] {
  const kwargs: string[] = [];
  const foreignKeyReference = renderRelationshipForeignKeyReference(model, field, schema, context);
  if (foreignKeyReference) {
    kwargs.push(`"foreign_keys": ${quotePythonString(foreignKeyReference)}`);
  }

  if (field.targetModel === model.name && !field.isList && field.relationToFields.length > 0 && !field.linkModelName) {
    kwargs.push(`"remote_side": ${quotePythonString(renderRemoteSideReference(model, field, context))}`);
  }

  return kwargs;
}

function findRelationCounterpart(
  targetModel: ModelDefinition | undefined,
  field: RelationFieldDefinition
): RelationFieldDefinition | undefined {
  return (
    targetModel?.relationFields.find((candidate) => candidate.name === field.backPopulates) ??
    targetModel?.relationFields.find(
      (candidate) => candidate.relationName === field.relationName && candidate.backPopulates === field.name
    ) ??
    targetModel?.relationFields.find((candidate) => candidate.backPopulates === field.name)
  );
}

function renderRemoteSideReference(
  model: ModelDefinition,
  field: RelationFieldDefinition,
  context: RenderContext
): string {
  const modelName = model.pythonName;
  const references = field.relationToFields.map((name) => `${modelName}.${resolveFieldPythonName(model.name, name, context)}`);
  return references.length === 1 ? references[0] : `[${references.join(", ")}]`;
}

function renderScalarAnnotation(field: ScalarFieldDefinition, context: RenderContext): string {
  const baseType = field.isList
    ? `list[${resolveTypeName(field.pythonType, context)}]`
    : resolveTypeName(field.pythonType, context);
  return field.isNullable || shouldSetDefaultNone(field) ? `${baseType} | None` : baseType;
}

function renderColumnType(
  field: ScalarFieldDefinition,
  model: ModelDefinition,
  schema: SchemaDefinition,
  context: RenderContext
): string {
  if (field.isList) {
    return `ARRAY(${renderBaseColumnType(field, model, context)})`;
  }

  return renderBaseColumnType(field, model, context);
}

function renderBaseColumnType(
  field: ScalarFieldDefinition,
  model: ModelDefinition,
  context: RenderContext
): string {
  if (shouldRenderNamedEnumColumn(field)) {
    const resolvedType = resolveTypeName(field.prismaType, context);
    const args = [`${resolvedType}`, `name=${quotePythonString(field.prismaType)}`];
    if (model.tableSchema) {
      args.push(`schema=${quotePythonString(model.tableSchema)}`);
    }
    return `SAEnum(${args.join(", ")})`;
  }

  if (field.nativeType?.name === "Json") {
    return "JSON()";
  }

  if (field.prismaType === "Json") {
    return "JSONB";
  }

  if (field.nativeType) {
    return renderNamedType(mapPostgresType(field.nativeType));
  }

  switch (field.prismaType) {
    case "String":
      return "String()";
    case "Boolean":
      return "Boolean()";
    case "Int":
      return "Integer()";
    case "BigInt":
      return "BigInteger()";
    case "Float":
      return "Float()";
    case "Decimal":
      return "Numeric()";
    case "Bytes":
      return "LargeBinary()";
    case "DateTime":
      return "DateTime()";
    default:
      return resolveTypeName(field.prismaType, context);
  }
}

function renderColumnDefault(
  field: ScalarFieldDefinition,
  context: RenderContext
): { column?: string; field?: string } {
  if (!field.hasDefaultValue || field.defaultValue === undefined) {
    return {};
  }

  if (typeof field.defaultValue === "string") {
    if (!isScalarPrismaType(field.prismaType)) {
      return { field: `default=${resolveTypeName(field.pythonType, context)}.${field.defaultValue}` };
    }
    return { field: `default=${quotePythonString(field.defaultValue)}` };
  }

  if (typeof field.defaultValue === "number" || typeof field.defaultValue === "boolean") {
    if (typeof field.defaultValue === "boolean") {
      return { field: `default=${field.defaultValue ? "True" : "False"}` };
    }
    return { field: `default=${String(field.defaultValue)}` };
  }

  if (field.defaultValue && typeof field.defaultValue === "object" && "name" in field.defaultValue) {
    const defaultValue = field.defaultValue as { name: unknown; args?: unknown[] };
    const name = String(defaultValue.name);
    const args = Array.isArray(defaultValue.args) ? defaultValue.args : [];

    switch (name) {
      case "autoincrement":
        return { column: "autoincrement=True" };
      case "uuid":
        return { field: "default_factory=uuid4" };
      case "now_client":
        return { field: "default_factory=lambda: datetime.now(timezone.utc)" };
      case "now":
        return { column: "server_default=func.now()" };
      case "dbgenerated":
        if (typeof args[0] === "string") {
          return { column: `server_default=text(${quotePythonString(args[0])})` };
        }
        return {};
      default:
        return {};
    }
  }

  return {};
}

function shouldSetDefaultNone(field: ScalarFieldDefinition): boolean {
  if (!field.hasDefaultValue) {
    return false;
  }

  if (field.defaultValue && typeof field.defaultValue === "object" && "name" in field.defaultValue) {
    return NONE_DEFAULT_FUNCTIONS.has(String(field.defaultValue.name));
  }

  return false;
}

function renderNamedType(mapping: { typeName: string; args: string[]; kwargs?: string[] }): string {
  const args = [...mapping.args];
  if (mapping.kwargs) {
    args.push(...mapping.kwargs);
  }
  return `${mapping.typeName}(${args.join(", ")})`;
}

function mapPostgresType(nativeType: NativeType): {
  typeName: string;
  args: string[];
  kwargs?: string[];
  importName?: string;
} {
  switch (nativeType.name) {
    case "VarChar":
      return { typeName: "VARCHAR", args: nativeType.args };
    case "Char":
      return { typeName: "CHAR", args: nativeType.args };
    case "Text":
      return { typeName: "TEXT", args: [] };
    case "Boolean":
      return { typeName: "BOOLEAN", args: [] };
    case "SmallInt":
      return { typeName: "SMALLINT", args: [] };
    case "Integer":
      return { typeName: "INTEGER", args: [] };
    case "BigInt":
      return { typeName: "BIGINT", args: [] };
    case "Real":
      return { typeName: "REAL", args: [] };
    case "DoublePrecision":
      return { typeName: "DOUBLE_PRECISION", args: [] };
    case "Decimal":
      return { typeName: "NUMERIC", args: nativeType.args };
    case "Timestamp":
      return {
        typeName: "TIMESTAMP",
        args: [],
        kwargs: nativeType.args[0] ? [`precision=${nativeType.args[0]}`] : undefined
      };
    case "Timestamptz":
      return {
        typeName: "TIMESTAMP",
        args: [],
        kwargs: [
          ...(nativeType.args[0] ? [`precision=${nativeType.args[0]}`] : []),
          "timezone=True"
        ]
      };
    case "Date":
      return { typeName: "DATE", args: [] };
    case "Time":
      return {
        typeName: "TIME",
        args: [],
        kwargs: nativeType.args[0] ? [`precision=${nativeType.args[0]}`] : undefined
      };
    case "Timetz":
      return {
        typeName: "TIME",
        args: [],
        kwargs: [
          ...(nativeType.args[0] ? [`precision=${nativeType.args[0]}`] : []),
          "timezone=True"
        ]
      };
    case "Json":
      return { typeName: "JSON", args: [] };
    case "JsonB":
      return { typeName: "JSONB", args: [] };
    case "ByteA":
      return { typeName: "BYTEA", args: [] };
    case "Uuid":
      // Aliased: a plain `UUID` import would shadow `uuid.UUID` used in annotations.
      return { typeName: "PG_UUID", args: ["as_uuid=True"], importName: "UUID as PG_UUID" };
    case "Xml":
      return { typeName: "XML", args: [] };
    case "Inet":
      return { typeName: "INET", args: [] };
    case "Citext":
      return { typeName: "CITEXT", args: [] };
    default:
      return { typeName: nativeType.name.toUpperCase(), args: nativeType.args };
  }
}

function isScalarPrismaType(type: string): boolean {
  return SCALAR_PRISMA_TYPES.has(type);
}

function resolveTypeName(typeName: string, context: RenderContext): string {
  return context.enumNameMap.get(typeName) ?? context.modelNameMap.get(typeName) ?? typeName;
}

function resolveFieldPythonName(modelName: string, fieldName: string, context: RenderContext): string {
  return context.fieldNameMap.get(modelName)?.get(fieldName) ?? fieldName;
}

function resolveScalarColumnName(model: ModelDefinition, fieldName: string): string {
  return model.scalarFields.find((candidate) => candidate.name === fieldName)?.columnName ?? fieldName;
}

function buildTargetColumnReference(schema: SchemaDefinition, targetModelName: string, targetFieldName: string): string {
  const targetModel = schema.models.find((model) => model.name === targetModelName);
  const targetField = targetModel?.scalarFields.find((candidate) => candidate.name === targetFieldName);
  const tableName = targetModel?.tableName ?? targetModelName;
  const schemaName = targetModel?.tableSchema;
  const columnName = targetField?.columnName ?? targetFieldName;
  return schemaName ? `${schemaName}.${tableName}.${columnName}` : `${tableName}.${columnName}`;
}

function shouldRenderNamedEnumColumn(field: ScalarFieldDefinition): boolean {
  return (
    field.prismaType !== "Json" &&
    field.prismaType !== "Unsupported" &&
    /^[A-Z][A-Za-z0-9_]*$/.test(field.prismaType) &&
    !field.nativeType &&
    !isScalarPrismaType(field.prismaType)
  );
}

function getForeignKeyFields(
  foreignKey: ScalarFieldDefinition["foreignKey"] | ForeignKeyDefinition | undefined
): string[] {
  if (!foreignKey) {
    return [];
  }

  return foreignKey.fields;
}

function getForeignKeyTargetFields(foreignKey: ForeignKeyDefinition): string[] {
  return foreignKey.targetFields;
}

function getForeignKeyFieldCount(
  foreignKey: ScalarFieldDefinition["foreignKey"] | ForeignKeyDefinition | undefined
): number {
  return getForeignKeyFields(foreignKey).length;
}
